# Generated by Django 2.2 on 2019-04-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
