# Generated by Django 2.2 on 2019-04-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20190415_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='course',
            field=models.CharField(choices=[('mn', 'Main Course'), ('st', 'Starters'), ('dt', 'Desserts')], max_length=20),
        ),
    ]
